Complete todo list
binodbhusal/ToDoList2 pull request #1
Opened 2023-05-08 21:52 UTC by binodbhusal

- Added to-do List functionality and created the module.
- Added HTML CSS for the to-do list.
- Completed all required functionality of the to-do list.

2023-05-09 17:22 UTC, yashodhicy commented on modules/functions.js
Excellent work on this code. You have used arrow functions which is a good practice in js. It is also better to use ES classes to make this code cleaner.

2023-05-10 04:18 UTC, yashodhicy requested changes
![200](https://github.com/binodbhusal/ToDoList2/assets/116276432/ea940546-708f-4daf-85fe-ed84eaa8d77a)
Hi @binodbhusal , You have done an excellent job so far. 


👍🏻 used HTML and CSS best practices
👍🏻 have used good variable names and appropriate arrow functions
👍🏻 have a clean code

but there are a few changes that need to be done to improve your beautiful code. look at the comment section for the requested change.

2023-05-12 10:12 UTC, yashodhicy approved these changes
great job so far.You are ready to go for next step. Congratulations
![congrats](https://github.com/binodbhusal/ToDoList2/assets/116276432/704bd6e4-3f62-41f3-bd5d-96e525e32860)

2023-05-12 10:12 UTC, yashodhicy commented on modules/functions.js
> +  const editTask = (index) => {
Excellent work on this code. You have used arrow functions which is a good practice in js. It is also better to use ES classes to make this code cleaner.`

2023-05-12 10:14 UTC, binodbhusal commented on modules/functions.js
> +  const editTask = (index) => {
@yashodhicy Thank you so much!!

2023-05-12 10:58 UTC, merged